version: '3.9'
services:

  users_backend:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - users_db

  users_db:
    image: mysql:8
    #    platform: linux/x86_64 #for m1 chip macs
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3307:3306"

